### PR TITLE
Set hand types as constants

### PR DESCRIPTION
**Pull request by TwelveNights**

### CODE REVIEW

**Comment by Futochu** [comment]
Since this is public code, it might be a good idea to go through the hand types and change "fuckup" to something more generally acceptable.  It's an excellent descriptor for the hand end state but some people might take it the wrong way.  Any suggestions?

**Comment by TwelveNights** [comment]
How about mistake?

**Comment by Futochu** [comment]
I can't think of anything better that is as concise.  Can you add this change?

**Comment by TwelveNights** [comment]
For now, we'll have to change the variable name to `MISTAKE`, but the name of the hand will still be `fuck_up` for the intents and purposes of the database. We'll have to do a database update for when we change that, which is up to you to do.

**Pull request merged**
